{"uuid": "e514a2f6-676a-4da0-afcb-df31e6cbb9cf", "children": ["b2be5704-8153-4e3b-870e-ed4b7a3cd6f0"], "afters": [{"name": "BuiltIn.Run Keyword If", "status": "failed", "statusDetails": {"message": "MaxRetryError: HTTPConnectionPool(host='localhost', port=50515): Max retries exceeded with url: /session/3cc1b8e507db0fe70732f6f73e754861/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028CD9562BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"}, "steps": [{"name": "SeleniumLibrary.Capture Page Screenshot", "status": "failed", "statusDetails": {"message": "MaxRetryError: HTTPConnectionPool(host='localhost', port=50515): Max retries exceeded with url: /session/3cc1b8e507db0fe70732f6f73e754861/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028CD9562BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"}, "attachments": [{"name": "Keyword Log", "source": "c7f45182-b4ef-4349-b195-8d407e394a4c-attachment.html", "type": "text/html"}], "start": 1755157741412, "stop": 1755157774122}], "stop": 1755157774122}]}